#define WIN32_LEAN_AND_MEAN
#define _WINSOCKAPI_
#include <winsock2.h>
#include <Windows.h>

#include "keycodes.h"

#include <string>
#include <unordered_map>

std::unordered_map<std::string, int> KeyCodes::key_code_map =
{
    {"None", -1},
    {"LeftMouseButton", VK_LBUTTON},
    {"RightMouseButton", VK_RBUTTON},
    {"ControlBreak", VK_CANCEL},
    {"MiddleMouseButton", VK_MBUTTON},
    {"X1MouseButton", VK_XBUTTON1},
    {"X2MouseButton", VK_XBUTTON2},
    {"Backspace", VK_BACK},
    {"Tab", VK_TAB},
    {"Clear", VK_CLEAR},
    {"Enter", VK_RETURN},
    {"Pause", VK_PAUSE},
    {"CapsLock", VK_CAPITAL},
    {"Escape", VK_ESCAPE},
    {"Space", VK_SPACE},
    {"PageUp", VK_PRIOR},
    {"PageDown", VK_NEXT},
    {"End", VK_END},
    {"Home", VK_HOME},
    {"LeftArrow", VK_LEFT},
    {"UpArrow", VK_UP},
    {"RightArrow", VK_RIGHT},
    {"DownArrow", VK_DOWN},
    {"Select", VK_SELECT},
    {"Print", VK_PRINT},
    {"Execute", VK_EXECUTE},
    {"PrintScreen", VK_SNAPSHOT},
    {"Ins", VK_INSERT},
    {"Delete", VK_DELETE},
    {"Help", VK_HELP},
    {"Key0", '0'},
    {"Key1", '1'},
    {"Key2", '2'},
    {"Key3", '3'},
    {"Key4", '4'},
    {"Key5", '5'},
    {"Key6", '6'},
    {"Key7", '7'},
    {"Key8", '8'},
    {"Key9", '9'},
    {"A", 'A'},
    {"B", 'B'},
    {"C", 'C'},
    {"D", 'D'},
    {"E", 'E'},
    {"F", 'F'},
    {"G", 'G'},
    {"H", 'H'},
    {"I", 'I'},
    {"J", 'J'},
    {"K", 'K'},
    {"L", 'L'},
    {"M", 'M'},
    {"N", 'N'},
    {"O", 'O'},
    {"P", 'P'},
    {"Q", 'Q'},
    {"R", 'R'},
    {"S", 'S'},
    {"T", 'T'},
    {"U", 'U'},
    {"V", 'V'},
    {"W", 'W'},
    {"X", 'X'},
    {"Y", 'Y'},
    {"Z", 'Z'},
    {"LeftWindowsKey", VK_LWIN},
    {"RightWindowsKey", VK_RWIN},
    {"Application", VK_APPS},
    {"Sleep", VK_SLEEP},
    {"NumpadKey0", VK_NUMPAD0},
    {"NumpadKey1", VK_NUMPAD1},
    {"NumpadKey2", VK_NUMPAD2},
    {"NumpadKey3", VK_NUMPAD3},
    {"NumpadKey4", VK_NUMPAD4},
    {"NumpadKey5", VK_NUMPAD5},
    {"NumpadKey6", VK_NUMPAD6},
    {"NumpadKey7", VK_NUMPAD7},
    {"NumpadKey8", VK_NUMPAD8},
    {"NumpadKey9", VK_NUMPAD9},
    {"Multiply", VK_MULTIPLY},
    {"Add", VK_ADD},
    {"Separator", VK_SEPARATOR},
    {"Subtract", VK_SUBTRACT},
    {"Decimal", VK_DECIMAL},
    {"Divide", VK_DIVIDE},
    {"F1", VK_F1},
    {"F2", VK_F2},
    {"F3", VK_F3},
    {"F4", VK_F4},
    {"F5", VK_F5},
    {"F6", VK_F6},
    {"F7", VK_F7},
    {"F8", VK_F8},
    {"F9", VK_F9},
    {"F10", VK_F10},
    {"F11", VK_F11},
    {"F12", VK_F12},
    {"NumLock", VK_NUMLOCK},
    {"ScrollLock", VK_SCROLL},
    {"LeftShift", VK_LSHIFT},
    {"RightShift", VK_RSHIFT},
    {"LeftControl", VK_LCONTROL},
    {"RightControl", VK_RCONTROL},
    {"LeftAlt", VK_LMENU},
    {"RightAlt", VK_RMENU},
    {"BrowserBack", VK_BROWSER_BACK},
    {"BrowserRefresh", VK_BROWSER_REFRESH},
    {"BrowserStop", VK_BROWSER_STOP},
    {"BrowserSearch", VK_BROWSER_SEARCH},
    {"BrowserFavorites", VK_BROWSER_FAVORITES},
    {"BrowserHome", VK_BROWSER_HOME},
    {"VolumeMute", VK_VOLUME_MUTE},
    {"VolumeDown", VK_VOLUME_DOWN},
    {"VolumeUp", VK_VOLUME_UP},
    {"NextTrack", VK_MEDIA_NEXT_TRACK},
    {"PreviousTrack", VK_MEDIA_PREV_TRACK},
    {"StopMedia", VK_MEDIA_STOP},
    {"PlayMedia", VK_MEDIA_PLAY_PAUSE},
    {"StartMailKey", VK_LAUNCH_MAIL},
    {"SelectMedia", VK_LAUNCH_MEDIA_SELECT},
    {"StartApplication1", VK_LAUNCH_APP1},
    {"StartApplication2", VK_LAUNCH_APP2}
};

std::unordered_map<std::string, std::string> KeyCodes::key_display_names =
{
    {"None", "无"},
    {"LeftMouseButton", "鼠标左键"},
    {"RightMouseButton", "鼠标右键"},
    {"ControlBreak", "Ctrl+Break"},
    {"MiddleMouseButton", "鼠标中键"},
    {"X1MouseButton", "鼠标侧键1"},
    {"X2MouseButton", "鼠标侧键2"},
    {"Backspace", "Backspace"},
    {"Tab", "Tab"},
    {"Clear", "Clear"},
    {"Enter", "Enter"},
    {"Pause", "Pause"},
    {"CapsLock", "CapsLock"},
    {"Escape", "Esc"},
    {"Space", "Space"},
    {"PageUp", "PageUp"},
    {"PageDown", "PageDown"},
    {"End", "End"},
    {"Home", "Home"},
    {"LeftArrow", "←"},
    {"UpArrow", "↑"},
    {"RightArrow", "→"},
    {"DownArrow", "↓"},
    {"Select", "Select"},
    {"Print", "Print"},
    {"Execute", "Execute"},
    {"PrintScreen", "PrtSc"},
    {"Ins", "Insert"},
    {"Delete", "Delete"},
    {"Help", "Help"},
    {"Key0", "0"},
    {"Key1", "1"},
    {"Key2", "2"},
    {"Key3", "3"},
    {"Key4", "4"},
    {"Key5", "5"},
    {"Key6", "6"},
    {"Key7", "7"},
    {"Key8", "8"},
    {"Key9", "9"},
    {"A", "A"},
    {"B", "B"},
    {"C", "C"},
    {"D", "D"},
    {"E", "E"},
    {"F", "F"},
    {"G", "G"},
    {"H", "H"},
    {"I", "I"},
    {"J", "J"},
    {"K", "K"},
    {"L", "L"},
    {"M", "M"},
    {"N", "N"},
    {"O", "O"},
    {"P", "P"},
    {"Q", "Q"},
    {"R", "R"},
    {"S", "S"},
    {"T", "T"},
    {"U", "U"},
    {"V", "V"},
    {"W", "W"},
    {"X", "X"},
    {"Y", "Y"},
    {"Z", "Z"},
    {"LeftWindowsKey", "Left Win"},
    {"RightWindowsKey", "Right Win"},
    {"Application", "Application"},
    {"Sleep", "Sleep"},
    {"NumpadKey0", "Num 0"},
    {"NumpadKey1", "Num 1"},
    {"NumpadKey2", "Num 2"},
    {"NumpadKey3", "Num 3"},
    {"NumpadKey4", "Num 4"},
    {"NumpadKey5", "Num 5"},
    {"NumpadKey6", "Num 6"},
    {"NumpadKey7", "Num 7"},
    {"NumpadKey8", "Num 8"},
    {"NumpadKey9", "Num 9"},
    {"Multiply", "Num *"},
    {"Add", "Num +"},
    {"Separator", "Separator"},
    {"Subtract", "Num -"},
    {"Decimal", "Num ."},
    {"Divide", "Num /"},
    {"F1", "F1"},
    {"F2", "F2"},
    {"F3", "F3"},
    {"F4", "F4"},
    {"F5", "F5"},
    {"F6", "F6"},
    {"F7", "F7"},
    {"F8", "F8"},
    {"F9", "F9"},
    {"F10", "F10"},
    {"F11", "F11"},
    {"F12", "F12"},
    {"NumLock", "NumLock"},
    {"ScrollLock", "ScrollLock"},
    {"LeftShift", "Left Shift"},
    {"RightShift", "Right Shift"},
    {"LeftControl", "Left Ctrl"},
    {"RightControl", "Right Ctrl"},
    {"LeftAlt", "Left Alt"},
    {"RightAlt", "Right Alt"},
    {"BrowserBack", "浏览器后退"},
    {"BrowserRefresh", "浏览器刷新"},
    {"BrowserStop", "浏览器停止"},
    {"BrowserSearch", "浏览器搜索"},
    {"BrowserFavorites", "浏览器收藏"},
    {"BrowserHome", "浏览器主页"},
    {"VolumeMute", "静音"},
    {"VolumeDown", "音量减"},
    {"VolumeUp", "音量加"},
    {"NextTrack", "下一曲"},
    {"PreviousTrack", "上一曲"},
    {"StopMedia", "停止"},
    {"PlayMedia", "播放/暂停"},
    {"StartMailKey", "邮件"},
    {"SelectMedia", "媒体选择"},
    {"StartApplication1", "应用1"},
    {"StartApplication2", "应用2"}
};

int KeyCodes::getKeyCode(const std::string& key_name) {
    auto it = key_code_map.find(key_name);
    if (it != key_code_map.end())
        return it->second;
    else
        return -1;
}